    ['deveste'] = {                            --DLC
        ['name'] = 'Deveste',
        ['brand'] = 'Principe',
        ['model'] = 'deveste',
        ['price'] = 234000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `deveste`,
        ['shop'] = 'luxury',
    },
    ['elegy'] = {                            --DLC
        ['name'] = 'Elegy Retro Custom',
        ['brand'] = 'Annis',
        ['model'] = 'elegy',
        ['price'] = 145000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `elegy`,
        ['shop'] = 'luxury',
    },
    ['elegy2'] = {
        ['name'] = 'Elegy RH8',
        ['brand'] = 'Annis',
        ['model'] = 'elegy2',
        ['price'] = 150000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `elegy2`,
        ['shop'] = 'luxury',
    },
    ['feltzer2'] = {
        ['name'] = 'Feltzer',
        ['brand'] = 'Benefactor',
        ['model'] = 'feltzer2',
        ['price'] = 97000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `feltzer2`,
        ['shop'] = 'luxury',
    },
    ['flashgt'] = {
        ['name'] = 'Flash GT',
        ['brand'] = 'Vapid',
        ['model'] = 'flashgt',
        ['price'] = 48000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `flashgt`,
        ['shop'] = 'luxury',
    },
    ['furoregt'] = {
        ['name'] = 'Furore GT',
        ['brand'] = 'Lampadati',
        ['model'] = 'furoregt',
        ['price'] = 78000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `furoregt`,
        ['shop'] = 'luxury',
    },
    ['futo'] = {
        ['name'] = 'Futo',
        ['brand'] = 'Karin',
        ['model'] = 'futo',
        ['price'] = 17500,
        ['category'] = 'coupes',
        ['categoryLabel'] = 'Coupes',
        ['hash'] = `futo`,
        ['shop'] = 'pdm',
    },
    ['gb200'] = {
        ['name'] = 'GB 200',
        ['brand'] = 'Vapid',
        ['model'] = 'gb200',
        ['price'] = 140000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gb200`,
        ['shop'] = 'luxury',
    },
    ['komoda'] = {
        ['name'] = 'Komoda',
        ['brand'] = 'Lampadati',
        ['model'] = 'komoda',
        ['price'] = 55000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `komoda`,
        ['shop'] = 'luxury',
    },
    ['imorgon'] = {
        ['name'] = 'Imorgon',
        ['brand'] = 'Överflöd',
        ['model'] = 'imorgon',
        ['price'] = 120000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `imorgon`,
        ['shop'] = 'luxury',
    },
    ['issi7'] = {                            --DLC
        ['name'] = 'Issi Sport',
        ['brand'] = 'Weeny',
        ['model'] = 'issi7',
        ['price'] = 100000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `issi7`,
        ['shop'] = 'pdm',
    },
    ['italigto'] = {                            --DLC
        ['name'] = 'Itali GTO',
        ['brand'] = 'Progen',
        ['model'] = 'italigto',
        ['price'] = 260000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `italigto`,
        ['shop'] = 'luxury',
    },
    ['jugular'] = {                            --DLC
        ['name'] = 'Jugular',
        ['brand'] = 'Ocelot',
        ['model'] = 'jugular',
        ['price'] = 80000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `jugular`,
        ['shop'] = 'luxury',
    },
    ['jester'] = {
        ['name'] = 'Jester',
        ['brand'] = 'Dinka',
        ['model'] = 'jester',
        ['price'] = 132250,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `jester`,
        ['shop'] = 'luxury',
    },
    ['jester2'] = {
        ['name'] = 'Jester Racecar',
        ['brand'] = 'Dinka',
        ['model'] = 'jester2',
        ['price'] = 210000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `jester2`,
        ['shop'] = 'luxury',
    },
    ['jester3'] = {
        ['name'] = 'Jester Classic',
        ['brand'] = 'Dinka',
        ['model'] = 'jester3',
        ['price'] = 85000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `jester3`,
        ['shop'] = 'luxury',
    },
    ['khamelion'] = {
        ['name'] = 'Khamelion',
        ['brand'] = 'Hijak',
        ['model'] = 'khamelion',
        ['price'] = 90000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `khamelion`,
        ['shop'] = 'luxury',
    },
    ['kuruma'] = {
        ['name'] = 'Kuruma',
        ['brand'] = 'Karin',
        ['model'] = 'kuruma',
        ['price'] = 72000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `kuruma`,
        ['shop'] = 'luxury',
    },
    ['kuruma2'] = {
        ['name'] = 'kuruma2',
        ['brand'] = 'Karin2',
        ['model'] = 'kuruma2',
        ['price'] = 72000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `kuruma2`,
        ['shop'] = 'luxury',
    },
    ['locust'] = {                            --DLC
        ['name'] = 'Locust',
        ['brand'] = 'Ocelot',
        ['model'] = 'locust',
        ['price'] = 200000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `locust`,
        ['shop'] = 'luxury',
    },
    ['lynx'] = {
        ['name'] = 'Lynx',
        ['brand'] = 'Ocelot',
        ['model'] = 'lynx',
        ['price'] = 150000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `lynx`,
        ['shop'] = 'luxury',
    },
    ['massacro'] = {
        ['name'] = 'Massacro',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'massacro',
        ['price'] = 110000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `massacro`,
        ['shop'] = 'luxury',
    },
    ['massacro2'] = {
        ['name'] = 'Massacro Racecar',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'massacro2',
        ['price'] = 80000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `massacro2`,
        ['shop'] = 'luxury',
    },
    ['neo'] = {                            --DLC
        ['name'] = 'Neo',
        ['brand'] = 'Vysser',
        ['model'] = 'neo',
        ['price'] = 230000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `neo`,
        ['shop'] = 'luxury',
    },
    ['neon'] = {                            --DLC
        ['name'] = 'Neon',
        ['brand'] = 'Pfister',
        ['model'] = 'neon',
        ['price'] = 220000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `neon`,
        ['shop'] = 'luxury',
    },
    ['ninef'] = {
        ['name'] = '9F',
        ['brand'] = 'Obey',
        ['model'] = 'ninef',
        ['price'] = 95000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `ninef`,
        ['shop'] = 'luxury',
    },
    ['ninef2'] = {
        ['name'] = '9F Cabrio',
        ['brand'] = 'Obey',
        ['model'] = 'ninef2',
        ['price'] = 105000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `ninef2`,
        ['shop'] = 'luxury',
    },
    ['omnis'] = {
        ['name'] = 'Omnis',
        ['brand'] = 'Wow',
        ['model'] = 'omnis',
        ['price'] = 90000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `omnis`,
        ['shop'] = 'luxury',
    },
    ['paragon'] = {                            --DLC
        ['name'] = 'Paragon',
        ['brand'] = 'Enus',
        ['model'] = 'paragon',
        ['price'] = 60000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `paragon`,
        ['shop'] = 'luxury',
    },
    ['pariah'] = {
        ['name'] = 'Pariah',
        ['brand'] = 'Ocelot',
        ['model'] = 'pariah',
        ['price'] = 90000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `pariah`,
        ['shop'] = 'luxury',
    },
    ['penumbra'] = {
        ['name'] = 'Penumbra',
        ['brand'] = 'Maibatsu',
        ['model'] = 'penumbra',
        ['price'] = 22000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `penumbra`,
        ['shop'] = 'luxury',
    },
    ['penumbra2'] = {
        ['name'] = 'Penumbra FF',
        ['brand'] = 'Maibatsu',
        ['model'] = 'penumbra2',
        ['price'] = 30000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `penumbra2`,
        ['shop'] = 'luxury',
    },
    ['rapidgt'] = {
        ['name'] = 'Rapid GT',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'rapidgt',
        ['price'] = 86000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `rapidgt`,
        ['shop'] = 'luxury',
    },
    ['rapidgt2'] = {
        ['name'] = 'Rapid GT Convertible',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'rapidgt2',
        ['price'] = 92000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `rapidgt2`,
        ['shop'] = 'luxury',
    },
    ['raptor'] = {
        ['name'] = 'Raptor',
        ['brand'] = 'BF',
        ['model'] = 'raptor',
        ['price'] = 90000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `raptor`,
        ['shop'] = 'luxury',
    },
    ['revolter'] = {
        ['name'] = 'Revolter',
        ['brand'] = 'Übermacht',
        ['model'] = 'revolter',
        ['price'] = 95000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `revolter`,
        ['shop'] = 'luxury',
    },
    ['ruston'] = {
        ['name'] = 'Ruston',
        ['brand'] = 'Hijak',
        ['model'] = 'ruston',
        ['price'] = 130000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `ruston`,
        ['shop'] = 'luxury',
    },
    ['schafter2'] = {
        ['name'] = 'Schafter',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter2',
        ['price'] = 16000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `schafter2`,
        ['shop'] = 'pdm',
    },
    ['schafter3'] = {
        ['name'] = 'Schafter V12',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter3',
        ['price'] = 35000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `schafter3`,
        ['shop'] = 'luxury',
    },
    ['schafter4'] = {
        ['name'] = 'Schafter LWB',
        ['brand'] = 'Benefactor',
        ['model'] = 'schafter4',
        ['price'] = 21000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `schafter4`,
        ['shop'] = 'luxury',
    },
    ['schlagen'] = {                            --DLC
        ['name'] = 'Schlagen GT',
        ['brand'] = 'Benefactor',
        ['model'] = 'schlagen',
        ['price'] = 160000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `schlagen`,
        ['shop'] = 'luxury',
    },
    ['schwarzer'] = {
        ['name'] = 'Schwartzer',
        ['brand'] = 'Benefactor',
        ['model'] = 'schwarzer',
        ['price'] = 47000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `schwarzer`,
        ['shop'] = 'luxury',
    },
    ['sentinel3'] = {
        ['name'] = 'Sentinel Classic',
        ['brand'] = 'Übermacht',
        ['model'] = 'sentinel3',
        ['price'] = 70000,
        ['category'] = 'coupes',
        ['categoryLabel'] = 'Coupes',
        ['hash'] = `sentinel3`,
        ['shop'] = 'pdm',
    },
    ['seven70'] = {
        ['name'] = 'Seven-70',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'seven70',
        ['price'] = 140000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `seven70`,
        ['shop'] = 'luxury',
    },
    ['specter'] = {
        ['name'] = 'Specter',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'specter',
        ['price'] = 160000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `specter`,
        ['shop'] = 'luxury',
    },
    ['streiter'] = {
        ['name'] = 'Streiter',
        ['brand'] = 'Benefactor',
        ['model'] = 'streiter',
        ['price'] = 40000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `streiter`,
        ['shop'] = 'luxury',
    },
    ['sugoi'] = {
        ['name'] = 'Sugoi',
        ['brand'] = 'Dinka',
        ['model'] = 'sugoi',
        ['price'] = 85000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `sugoi`,
        ['shop'] = 'luxury',
    },
    ['sultan'] = {
        ['name'] = 'Sultan',
        ['brand'] = 'Karin',
        ['model'] = 'sultan',
        ['price'] = 50000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `sultan`,
        ['shop'] = 'luxury',
    },
    ['sultan2'] = {
        ['name'] = 'Sultan Custom',
        ['brand'] = 'Karin',
        ['model'] = 'sultan2',
        ['price'] = 55000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `sultan2`,
        ['shop'] = 'luxury',
    },
    ['surano'] = {
        ['name'] = 'Surano',
        ['brand'] = 'Benefactor',
        ['model'] = 'surano',
        ['price'] = 80000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `surano`,
        ['shop'] = 'luxury',
    },
    ['tampa2'] = {
        ['name'] = 'Drift Tampa',
        ['brand'] = 'Declasse',
        ['model'] = 'tampa2',
        ['price'] = 80000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `tampa2`,
        ['shop'] = 'pdm',
    },
    ['tropos'] = {
        ['name'] = 'Tropos Rallye',
        ['brand'] = 'Lampadati',
        ['model'] = 'tropos',
        ['price'] = 65000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `tropos`,
        ['shop'] = 'luxury',
    },
    ['verlierer2'] = {
        ['name'] = 'Verlierer',
        ['brand'] = 'Bravado',
        ['model'] = 'verlierer2',
        ['price'] = 90500,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `verlierer2`,
        ['shop'] = 'luxury',
    },
    ['vstr'] = {
        ['name'] = 'V-STR',
        ['brand'] = 'Albany',
        ['model'] = 'vstr',
        ['price'] = 80000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `vstr`,
        ['shop'] = 'luxury',
    },
    ['italirsx'] = {
        ['name'] = 'Itali RSX',
        ['brand'] = 'Progen',
        ['model'] = 'italirsx',
        ['price'] = 260000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `italirsx`,
        ['shop'] = 'luxury',
    },
    ['zr350'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'ZR350',
        ['brand'] = 'Annis',
        ['model'] = 'zr350',
        ['price'] = 38000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `zr350`,
        ['shop'] = 'luxury',
    },
    ['calico'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Calico GTF',
        ['brand'] = 'Karin',
        ['model'] = 'calico',
        ['price'] = 39000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `calico`,
        ['shop'] = 'luxury',
    },
    ['futo2'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Futo GTX',
        ['brand'] = 'Karin',
        ['model'] = 'futo2',
        ['price'] = 39000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `futo2`,
        ['shop'] = 'luxury',
    },
    ['euros'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Euros',
        ['brand'] = 'Annis',
        ['model'] = 'euros',
        ['price'] = 80000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `euros`,
        ['shop'] = 'luxury',
    },
    ['jester4'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Jester RR',
        ['brand'] = 'Dinka',
        ['model'] = 'jester4',
        ['price'] = 240000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `jester4`,
        ['shop'] = 'luxury',
    },
    ['remus'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Remus',
        ['brand'] = 'Annis',
        ['model'] = 'remus',
        ['price'] = 48000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `remus`,
        ['shop'] = 'luxury',
    },
    ['comet6'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Comet S2',
        ['brand'] = 'Pfister',
        ['model'] = 'comet6',
        ['price'] = 230000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `comet6`,
        ['shop'] = 'luxury',
    },
    ['growler'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Growler',
        ['brand'] = 'Pfister',
        ['model'] = 'growler',
        ['price'] = 205000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `growler`,
        ['shop'] = 'luxury',
    },
    ['vectre'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Vectre',
        ['brand'] = 'Emperor',
        ['model'] = 'vectre',
        ['price'] = 80000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `vectre`,
        ['shop'] = 'luxury',
    },
    ['cypher'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Cypher',
        ['brand'] = 'Übermacht',
        ['model'] = 'cypher',
        ['price'] = 155000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `cypher`,
        ['shop'] = 'luxury',
    },
    ['sultan3'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Sultan Classic Custom',
        ['brand'] = 'Karin',
        ['model'] = 'sultan3',
        ['price'] = 56000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `sultan3`,
        ['shop'] = 'luxury',
    },
    ['rt3000'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'RT3000',
        ['brand'] = 'Dinka',
        ['model'] = 'rt3000',
        ['price'] = 65000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `rt3000`,
        ['shop'] = 'luxury',
    },
    --- Sports Classic
    ['ardent'] = {
        ['name'] = 'Ardent',
        ['brand'] = 'Ocelot',
        ['model'] = 'ardent',
        ['price'] = 30000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `ardent`,
        ['shop'] = 'pdm',
    },
    ['btype'] = {              --meme car that goes pretty fast
        ['name'] = 'Roosevelt',
        ['brand'] = 'Albany',
        ['model'] = 'btype',
        ['price'] = 75000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `btype`,
        ['shop'] = 'pdm',
    },
    ['btype2'] = {
        ['name'] = 'Franken Stange',
        ['brand'] = 'Albany',
        ['model'] = 'btype2',
        ['price'] = 87000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `btype2`,
        ['shop'] = 'pdm',
    },
    ['btype3'] = {
        ['name'] = 'Roosevelt Valor',
        ['brand'] = 'Albany',
        ['model'] = 'btype3',
        ['price'] = 63000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `btype3`,
        ['shop'] = 'pdm',
    },
    ['casco'] = {
        ['name'] = 'Casco',
        ['brand'] = 'Lampadati',
        ['model'] = 'casco',
        ['price'] = 100000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `casco`,
        ['shop'] = 'pdm',
    },
    ['cheetah2'] = {
        ['name'] = 'Cheetah Classic',
        ['brand'] = 'Grotti',
        ['model'] = 'cheetah2',
        ['price'] = 195000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `cheetah2`,
        ['shop'] = 'luxury',
    },
    ['deluxo'] = {
        ['name'] = 'Deluxo',
        ['brand'] = 'Imponte',
        ['model'] = 'deluxo',
        ['price'] = 55000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `deluxo`,
        ['shop'] = 'pdm',
    },
    ['dynasty'] = {                            --DLC
        ['name'] = 'Dynasty',
        ['brand'] = 'Weeny',
        ['model'] = 'dynasty',
        ['price'] = 25000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `dynasty`,
        ['shop'] = 'pdm',
    },
    ['fagaloa'] = {
        ['name'] = 'Fagaloa',
        ['brand'] = 'Vulcar',
        ['model'] = 'fagaloa',
        ['price'] = 13000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `fagaloa`,
        ['shop'] = 'pdm',
    },
    ['feltzer3'] = {                            --DLC
        ['name'] = 'Stirling GT',
        ['brand'] = 'Benefactor',
        ['model'] = 'feltzer3',
        ['price'] = 115000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `feltzer3`,
        ['shop'] = 'pdm',
    },
    ['gt500'] = {
        ['name'] = 'GT500',
        ['brand'] = 'Grotti',
        ['model'] = 'gt500',
        ['price'] = 130000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `gt500`,
        ['shop'] = 'pdm',
    },
    ['infernus2'] = {
        ['name'] = 'Infernus Classic',
        ['brand'] = 'Pegassi',
        ['model'] = 'infernus2',
        ['price'] = 245000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `infernus2`,
        ['shop'] = 'pdm',
    },
    ['jb700'] = {
        ['name'] = 'JB 700',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'jb700',
        ['price'] = 240000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `jb700`,
        ['shop'] = 'pdm',
    },
    ['jb7002'] = {
        ['name'] = 'JB 700W',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'jb7002',
        ['price'] = 40000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `jb7002`,
        ['shop'] = 'pdm',
    },
    ['mamba'] = {
        ['name'] = 'Mamba',
        ['brand'] = 'Declasse',
        ['model'] = 'mamba',
        ['price'] = 140000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `mamba`,
        ['shop'] = 'pdm',
    },
    ['manana'] = {
        ['name'] = 'Manana',
        ['brand'] = 'Albany',
        ['model'] = 'manana',
        ['price'] = 12800,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `manana`,
        ['shop'] = 'pdm',
    },
    ['manana2'] = {
        ['name'] = 'Manana Custom',
        ['brand'] = 'Albany',
        ['model'] = 'manana2',
        ['price'] = 24000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `manana2`,
        ['shop'] = 'pdm',
    },
    ['michelli'] = {
        ['name'] = 'Michelli GT',
        ['brand'] = 'Lampadati',
        ['model'] = 'michelli',
        ['price'] = 30000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `michelli`,
        ['shop'] = 'pdm',
    },
    ['monroe'] = {
        ['name'] = 'Monroe',
        ['brand'] = 'Pegassi',
        ['model'] = 'monroe',
        ['price'] = 115000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `monroe`,
        ['shop'] = 'pdm',
    },
    ['nebula'] = {                            --DLC
        ['name'] = 'Nebula',
        ['brand'] = 'Vulcar',
        ['model'] = 'nebula',
        ['price'] = 22000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `nebula`,
        ['shop'] = 'pdm',
    },
    ['peyote'] = {
        ['name'] = 'Peyote',
        ['brand'] = 'Vapid',
        ['model'] = 'peyote',
        ['price'] = 23500,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `peyote`,
        ['shop'] = 'pdm',
    },
    ['peyote3'] = {
        ['name'] = 'Peyote Custom',
        ['brand'] = 'Vapid',
        ['model'] = 'peyote3',
        ['price'] = 48000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `peyote3`,
        ['shop'] = 'pdm',
    },
    ['pigalle'] = {
        ['name'] = 'Pigalle',
        ['brand'] = 'Lampadati',
        ['model'] = 'pigalle',
        ['price'] = 92000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `pigalle`,
        ['shop'] = 'pdm',
    },
    ['rapidgt3'] = {
        ['name'] = 'Rapid GT Classic',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'rapidgt3',
        ['price'] = 90000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `rapidgt3`,
        ['shop'] = 'pdm',
    },
    ['retinue'] = {
        ['name'] = 'Retinue',
        ['brand'] = 'Vapid',
        ['model'] = 'retinue',
        ['price'] = 32000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `retinue`,
        ['shop'] = 'pdm',
    },
    ['retinue2'] = {
        ['name'] = 'Retinue MKII',
        ['brand'] = 'Vapid',
        ['model'] = 'retinue2',
        ['price'] = 38000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `retinue2`,
        ['shop'] = 'pdm',
    },
    ['savestra'] = {
        ['name'] = 'Savestra',
        ['brand'] = 'Annis',
        ['model'] = 'savestra',
        ['price'] = 67000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `savestra`,
        ['shop'] = 'pdm',
    },
    ['stinger'] = {
        ['name'] = 'Stinger',
        ['brand'] = 'Grotti',
        ['model'] = 'stinger',
        ['price'] = 39500,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `stinger`,
        ['shop'] = 'pdm',
    },
    ['stingergt'] = {
        ['name'] = 'Stinger GT',
        ['brand'] = 'Grotti',
        ['model'] = 'stingergt',
        ['price'] = 70000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `stingergt`,
        ['shop'] = 'pdm',
    },
    ['stromberg'] = {
        ['name'] = 'Stromberg',
        ['brand'] = 'Ocelot',
        ['model'] = 'stromberg',
        ['price'] = 80000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `stromberg`,
        ['shop'] = 'pdm',
    },
    ['swinger'] = {                            --DLC
        ['name'] = 'Swinger',
        ['brand'] = 'Ocelot',
        ['model'] = 'swinger',
        ['price'] = 221000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `swinger`,
        ['shop'] = 'pdm',
    },
    ['torero'] = {
        ['name'] = 'Torero',
        ['brand'] = 'Pegassi',
        ['model'] = 'torero',
        ['price'] = 84000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `torero`,
        ['shop'] = 'pdm',
    },
    ['tornado'] = {
        ['name'] = 'Tornado',
        ['brand'] = 'Declasse',
        ['model'] = 'tornado',
        ['price'] = 21000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `tornado`,
        ['shop'] = 'pdm',
    },
    ['tornado2'] = {
        ['name'] = 'Tornado Convertible',
        ['brand'] = 'Declasse',
        ['model'] = 'tornado2',
        ['price'] = 22000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `tornado2`,
        ['shop'] = 'pdm',
    },
    ['tornado5'] = {
        ['name'] = 'Tornado Custom',
        ['brand'] = 'Declasse',
        ['model'] = 'tornado5',
        ['price'] = 22000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `tornado5`,
        ['shop'] = 'pdm',
    },
    ['turismo2'] = {
        ['name'] = 'Turismo Classic',
        ['brand'] = 'Grotti',
        ['model'] = 'turismo2',
        ['price'] = 170000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `turismo2`,
        ['shop'] = 'pdm',
    },
    ['viseris'] = {
        ['name'] = 'Viseris',
        ['brand'] = 'Lampadati',
        ['model'] = 'viseris',
        ['price'] = 210000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `viseris`,
        ['shop'] = 'pdm',
    },
    ['z190'] = {
        ['name'] = '190Z',
        ['brand'] = 'Karin',
        ['model'] = 'z190',
        ['price'] = 78000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `z190`,
        ['shop'] = 'pdm',
    },
    ['ztype'] = {
        ['name'] = 'Z-Type',
        ['brand'] = 'Truffade',
        ['model'] = 'ztype',
        ['price'] = 270000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `ztype`,
        ['shop'] = 'pdm',
    },
    ['zion3'] = {                            --DLC
        ['name'] = 'Zion Classic',
        ['brand'] = 'Übermacht',
        ['model'] = 'zion3',
        ['price'] = 45000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `zion3`,
        ['shop'] = 'pdm',
    },
    ['cheburek'] = {
        ['name'] = 'Cheburek',
        ['brand'] = 'Rune',
        ['model'] = 'cheburek',
        ['price'] = 7000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `cheburek`,
        ['shop'] = 'pdm',
    },
    ['toreador'] = {
        ['name'] = 'Toreador',
        ['brand'] = 'Pegassi',
        ['model'] = 'toreador',
        ['price'] = 50000,
        ['category'] = 'sportsclassics',
        ['categoryLabel'] = 'Sports Classics',
        ['hash'] = `toreador`,
        ['shop'] = 'pdm',
    },
    --- Super
    ['adder'] = {
        ['name'] = 'Adder',
        ['brand'] = 'Truffade',
        ['model'] = 'adder',
        ['price'] = 280000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `adder`,
        ['shop'] = 'luxury',
    },
    ['autarch'] = {
        ['name'] = 'Autarch',
        ['brand'] = 'Överflöd',
        ['model'] = 'autarch',
        ['price'] = 224000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `autarch`,
        ['shop'] = 'luxury',
    },
    ['banshee2'] = {
        ['name'] = 'Banshee 900R',
        ['brand'] = 'Bravado',
        ['model'] = 'banshee2',
        ['price'] = 120000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `banshee2`,
        ['shop'] = 'luxury',
    },
    ['bullet'] = {
        ['name'] = 'Bullet',
        ['brand'] = 'Vapid',
        ['model'] = 'bullet',
        ['price'] = 120000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `bullet`,
        ['shop'] = 'luxury',
    },
    ['cheetah'] = {
        ['name'] = 'Cheetah',
        ['brand'] = 'Grotti',
        ['model'] = 'cheetah',
        ['price'] = 214000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `cheetah`,
        ['shop'] = 'luxury',
    },
    ['cyclone'] = {         --might be too overpowered
        ['name'] = 'Cyclone',
        ['brand'] = 'Coil',
        ['model'] = 'cyclone',
        ['price'] = 300000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `cyclone`,
        ['shop'] = 'luxury',
    },
    ['entity2'] = {
        ['name'] = 'Entity XXR',
        ['brand'] = 'Överflöd',
        ['model'] = 'entity2',
        ['price'] = 164000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `entity2`,
        ['shop'] = 'luxury',
    },
    ['entityxf'] = {
        ['name'] = 'Entity XF',
        ['brand'] = 'Överflöd',
        ['model'] = 'entityxf',
        ['price'] = 180000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `entityxf`,
        ['shop'] = 'luxury',
    },
    ['emerus'] = {                            --DLC
        ['name'] = 'Emerus',
        ['brand'] = 'Progen',
        ['model'] = 'emerus',
        ['price'] = 220000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `emerus`,
        ['shop'] = 'luxury',
    },
    ['fmj'] = {
        ['name'] = 'FMJ',
        ['brand'] = 'Vapid',
        ['model'] = 'fmj',
        ['price'] = 125000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `fmj`,
        ['shop'] = 'luxury',
    },
    ['furia'] = {
        ['name'] = 'Furia',
        ['brand'] = 'Grotti',
        ['model'] = 'furia',
        ['price'] = 230000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `furia`,
        ['shop'] = 'luxury',
    },
    ['gp1'] = {
        ['name'] = 'GP1',
        ['brand'] = 'Progen',
        ['model'] = 'gp1',
        ['price'] = 110000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gp1`,
        ['shop'] = 'luxury',
    },
    ['infernus'] = {
        ['name'] = 'Infernus',
        ['brand'] = 'Pegassi',
        ['model'] = 'infernus',
        ['price'] = 235000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `infernus`,
        ['shop'] = 'luxury',
    },
    ['italigtb'] = {
        ['name'] = 'Itali GTB',
        ['brand'] = 'Progen',
        ['model'] = 'italigtb',
        ['price'] = 170000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `italigtb`,
        ['shop'] = 'luxury',
    },
    ['italigtb2'] = {
        ['name'] = 'Itali GTB Custom',
        ['brand'] = 'Progen',
        ['model'] = 'italigtb2',
        ['price'] = 250000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `italigtb2`,
        ['shop'] = 'luxury',
    },
    ['krieger'] = {                            --DLC
        ['name'] = 'Krieger',
        ['brand'] = 'Benefactor',
        ['model'] = 'krieger',
        ['price'] = 222000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `krieger`,
        ['shop'] = 'luxury',
    },
    ['le7b'] = {
        ['name'] = 'RE-7B',
        ['brand'] = 'Annis',
        ['model'] = 'le7b',
        ['price'] = 260000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `le7b`,
        ['shop'] = 'luxury',
    },
    ['nero'] = {
        ['name'] = 'Nero',
        ['brand'] = 'Truffade',
        ['model'] = 'nero',
        ['price'] = 200000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `nero`,
        ['shop'] = 'luxury',
    },
    ['nero2'] = {
        ['name'] = 'Nero Custom',
        ['brand'] = 'Truffade',
        ['model'] = 'nero2',
        ['price'] = 260000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `nero2`,
        ['shop'] = 'luxury',
    },
    ['osiris'] = {
        ['name'] = 'Osiris',
        ['brand'] = 'Pegassi',
        ['model'] = 'osiris',
        ['price'] = 220000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `osiris`,
        ['shop'] = 'luxury',
    },
    ['penetrator'] = {
        ['name'] = 'Penetrator',
        ['brand'] = 'Ocelot',
        ['model'] = 'penetrator',
        ['price'] = 130000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `penetrator`,
        ['shop'] = 'luxury',
    },
    ['pfister811'] = {
        ['name'] = '811',
        ['brand'] = 'Pfister',
        ['model'] = 'pfister811',
        ['price'] = 220000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `pfister811`,
        ['shop'] = 'luxury',
    },
    ['prototipo'] = {
        ['name'] = 'X80 Proto',
        ['brand'] = 'Grotti',
        ['model'] = 'prototipo',
        ['price'] = 235000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `prototipo`,
        ['shop'] = 'luxury',
    },
    ['reaper'] = {
        ['name'] = 'Reaper',
        ['brand'] = 'Pegassi',
        ['model'] = 'reaper',
        ['price'] = 100000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `reaper`,
        ['shop'] = 'luxury',
    },
    ['s80'] = {                            --DLC
        ['name'] = 'S80RR',
        ['brand'] = 'Annis',
        ['model'] = 's80',
        ['price'] = 205000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `s80`,
        ['shop'] = 'luxury',
    },
    ['sc1'] = {
        ['name'] = 'SC1',
        ['brand'] = 'Übermacht',
        ['model'] = 'sc1',
        ['price'] = 90000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `sc1`,
        ['shop'] = 'luxury',
    },
    ['sheava'] = {                            --DLC
        ['name'] = 'ETR1',
        ['brand'] = 'Emperor',
        ['model'] = 'sheava',
        ['price'] = 220000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `sheava`,
        ['shop'] = 'luxury',
    },
    ['sultanrs'] = {
        ['name'] = 'Sultan RS',
        ['brand'] = 'Karin',
        ['model'] = 'sultanrs',
        ['price'] = 76500,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `sultanrs`,
        ['shop'] = 'luxury',
    },
    ['t20'] = {
        ['name'] = 'T20',
        ['brand'] = 'Progen',
        ['model'] = 't20',
        ['price'] = 1650000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `t20`,
        ['shop'] = 'luxury',
    },
    ['taipan'] = {
        ['name'] = 'Taipan',
        ['brand'] = 'Cheval',
        ['model'] = 'taipan',
        ['price'] = 1850000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `taipan`,
        ['shop'] = 'luxury',
    },
    ['tempesta'] = {
        ['name'] = 'Tempesta',
        ['brand'] = 'Pegassi',
        ['model'] = 'tempesta',
        ['price'] = 120000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `tempesta`,
        ['shop'] = 'luxury',
    },
    ['tezeract'] = {
        ['name'] = 'Tezeract',
        ['brand'] = 'Pegassi',
        ['model'] = 'tezeract',
        ['price'] = 220000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `tezeract`,
        ['shop'] = 'luxury',
    },
    ['thrax'] = {                            --DLC
        ['name'] = 'Thrax',
        ['brand'] = 'Truffade',
        ['model'] = 'thrax',
        ['price'] = 180000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `thrax`,
        ['shop'] = 'luxury',
    },
    ['tigon'] = {
        ['name'] = 'Tigon',
        ['brand'] = 'Lampadati',
        ['model'] = 'tigon',
        ['price'] = 240000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `tigon`,
        ['shop'] = 'luxury',
    },
    ['turismor'] = {
        ['name'] = 'Turismo R',
        ['brand'] = 'Grotti',
        ['model'] = 'turismor',
        ['price'] = 140000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `turismor`,
        ['shop'] = 'luxury',
    },
    ['tyrant'] = {
        ['name'] = 'Tyrant',
        ['brand'] = 'Överflöd',
        ['model'] = 'tyrant',
        ['price'] = 2100000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `tyrant`,
        ['shop'] = 'luxury',
    },
    ['tyrus'] = {
        ['name'] = 'Tyrus',
        ['brand'] = 'Progen',
        ['model'] = 'tyrus',
        ['price'] = 230000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `tyrus`,
        ['shop'] = 'luxury',
    },
    ['vacca'] = {
        ['name'] = 'Vacca',
        ['brand'] = 'Pegassi',
        ['model'] = 'vacca',
        ['price'] = 105000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `vacca`,
        ['shop'] = 'luxury',
    },
    ['vagner'] = {
        ['name'] = 'Vagner',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'vagner',
        ['price'] = 1660000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `vagner`,
        ['shop'] = 'luxury',
    },
    ['visione'] = {
        ['name'] = 'Visione',
        ['brand'] = 'Grotti',
        ['model'] = 'visione',
        ['price'] = 750000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `visione`,
        ['shop'] = 'luxury',
    },
    ['voltic'] = {
        ['name'] = 'Voltic',
        ['brand'] = 'Coil',
        ['model'] = 'voltic',
        ['price'] = 120000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `voltic`,
        ['shop'] = 'luxury',
    },
    ['voltic2'] = {
        ['name'] = 'Rocket Voltic',
        ['brand'] = 'Coil',
        ['model'] = 'voltic2',
        ['price'] = 9830400,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `voltic2`,
        ['shop'] = 'luxury',
    },
    ['xa21'] = {
        ['name'] = 'XA-21',
        ['brand'] = 'Ocelot',
        ['model'] = 'xa21',
        ['price'] = 180000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `xa21`,
        ['shop'] = 'luxury',
    },
    ['zentorno'] = {
        ['name'] = 'Zentorno',
        ['brand'] = 'Pegassi',
        ['model'] = 'zentorno',
        ['price'] = 340000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `zentorno`,
        ['shop'] = 'luxury',
    },
    ['zorrusso'] = {                            --DLC
        ['name'] = 'Zorrusso',
        ['brand'] = 'Pegassi',
        ['model'] = 'zorrusso',
        ['price'] = 277000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `zorrusso`,
        ['shop'] = 'luxury',
    },
    -- Vans
    ['bison'] = {
        ['name'] = 'Bison',
        ['brand'] = 'Bravado',
        ['model'] = 'bison',
        ['price'] = 18000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `bison`,
        ['shop'] = 'pdm',
    },
    ['bobcatxl'] = {
        ['name'] = 'Bobcat XL Open',
        ['brand'] = 'Vapid',
        ['model'] = 'bobcatxl',
        ['price'] = 13500,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `bobcatxl`,
        ['shop'] = 'pdm',
    },
    ['burrito3'] = {
        ['name'] = 'Burrito',
        ['brand'] = 'Declasse',
        ['model'] = 'burrito3',
        ['price'] = 4000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `burrito3`,
        ['shop'] = 'pdm',
    },
    ['gburrito2'] = {
        ['name'] = 'Burrito Custom',
        ['brand'] = 'Declasse',
        ['model'] = 'gburrito2',
        ['price'] = 11500,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gburrito2`,
        ['shop'] = 'pdm',
    },
    ['rumpo'] = {
        ['name'] = 'Rumpo',
        ['brand'] = 'Bravado',
        ['model'] = 'rumpo',
        ['price'] = 9000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `rumpo`,
        ['shop'] = 'pdm',
    },
    ['journey'] = {
        ['name'] = 'Journey',
        ['brand'] = 'Zirconium',
        ['model'] = 'journey',
        ['price'] = 6500,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `journey`,
        ['shop'] = 'pdm',
    },
    ['minivan'] = {
        ['name'] = 'Minivan',
        ['brand'] = 'Vapid',
        ['model'] = 'minivan',
        ['price'] = 7000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `minivan`,
        ['shop'] = 'pdm',
    },
    ['minivan2'] = {
        ['name'] = 'Minivan Custom',
        ['brand'] = 'Vapid',
        ['model'] = 'minivan2',
        ['price'] = 10000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `minivan2`,
        ['shop'] = 'pdm',
    },
    ['paradise'] = {
        ['name'] = 'Paradise',
        ['brand'] = 'Bravado',
        ['model'] = 'paradise',
        ['price'] = 9000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `paradise`,
        ['shop'] = 'pdm',
    },
    ['rumpo3'] = {
        ['name'] = 'Rumpo Custom',
        ['brand'] = 'Bravado',
        ['model'] = 'rumpo3',
        ['price'] = 19500,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `rumpo3`,
        ['shop'] = 'pdm',
    },
    ['speedo'] = {
        ['name'] = 'Speedo',
        ['brand'] = 'Vapid',
        ['model'] = 'speedo',
        ['price'] = 10000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `speedo`,
        ['shop'] = 'pdm',
    },
    ['speedo4'] = {
        ['name'] = 'Speedo Custom',
        ['brand'] = 'Vapid',
        ['model'] = 'speedo4',
        ['price'] = 15000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `speedo4`,
        ['shop'] = 'pdm',
    },
    ['surfer'] = {
        ['name'] = 'Surfer',
        ['brand'] = 'BF',
        ['model'] = 'surfer',
        ['price'] = 9000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `surfer`,
        ['shop'] = 'pdm',
    },
    ['youga3'] = {
        ['name'] = 'Youga Classic 4x4',
        ['brand'] = 'Bravado',
        ['model'] = 'youga3',
        ['price'] = 15000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `youga3`,
        ['shop'] = 'pdm',
    },
    ['youga'] = {
        ['name'] = 'Youga',
        ['brand'] = 'Bravado',
        ['model'] = 'youga',
        ['price'] = 8000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `youga`,
        ['shop'] = 'pdm',
    },
    ['youga2'] = {
        ['name'] = 'Youga Classic',
        ['brand'] = 'Bravado',
        ['model'] = 'youga2',
        ['price'] = 14500,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `youga2`,
        ['shop'] = 'pdm',
    },
    ['youga4'] = {          --DLC +set sv_enforceGameBuild 2545
        ['name'] = 'Youga Custom',
        ['brand'] = 'Bravado',
        ['model'] = 'youga4',
        ['price'] = 85000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `youga4`,
        ['shop'] = 'pdm',
    },
    -- Utility
    ['sadler'] = {
        ['name'] = 'Sadler',
        ['brand'] = 'Vapid',
        ['model'] = 'sadler',
        ['price'] = 20000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Off Road',
        ['hash'] = `sadler`,
        ['shop'] = 'pdm',
    },
    ['slamtruck'] = {
        ['name'] = 'Slam Truck',
        ['brand'] = 'Vapid',
        ['model'] = 'slamtruck',
        ['price'] = 100000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `slamtruck`,
        ['shop'] = 'pdm',
    },
    ['warrener2'] = {                            --DLC +set sv_enforceGameBuild 2372
        ['name'] = 'Warrener HKR',
        ['brand'] = 'Vulcar',
        ['model'] = 'warrener2',
        ['price'] = 30000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `warrener2`,
        ['shop'] = 'pdm',
    },
        -- Boats
    ['squalo'] = {
        ['name'] = 'Squalo',
        ['brand'] = 'Shitzu',
        ['model'] = 'squalo',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `squalo`,
        ['shop'] = 'boats',
    },
    ['marquis'] = {
        ['name'] = 'Marquis',
        ['brand'] = 'Dinka',
        ['model'] = 'marquis',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `marquis`,
        ['shop'] = 'boats',
    },
    ['seashark'] = {
        ['name'] = 'Seashark',
        ['brand'] = 'Speedophile',
        ['model'] = 'seashark',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `seashark`,
        ['shop'] = 'boats',
    },
    ['seashark2'] = {
        ['name'] = 'Seashark Lifeguard',
        ['brand'] = 'Speedophile',
        ['model'] = 'seashark2',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `seashark2`,
        ['shop'] = 'boats',
    },
    ['seashark3'] = {
        ['name'] = 'Seashark Yacht',
        ['brand'] = 'Speedophile',
        ['model'] = 'seashark3',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `seashark3`,
        ['shop'] = 'boats',
    },
    ['jetmax'] = {
        ['name'] = 'Jetmax',
        ['brand'] = 'Shitzu',
        ['model'] = 'jetmax',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `jetmax`,
        ['shop'] = 'boats',
    },
    ['tropic'] = {
        ['name'] = 'Tropic',
        ['brand'] = 'Shitzu',
        ['model'] = 'tropic',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `tropic`,
        ['shop'] = 'boats',
    },
    ['tropic2'] = {
        ['name'] = 'Tropic Yacht',
        ['brand'] = 'Shitzu',
        ['model'] = 'tropic2',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `tropic2`,
        ['shop'] = 'boats',
    },
    ['dinghy'] = {
        ['name'] = 'Dinghy 2-Seater',
        ['brand'] = 'Nagasaki',
        ['model'] = 'dinghy',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `dinghy`,
        ['shop'] = 'boats',
    },
    ['dinghy2'] = {
        ['name'] = 'Dinghy 4-Seater',
        ['brand'] = 'Nagasaki',
        ['model'] = 'dinghy2',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `dinghy2`,
        ['shop'] = 'boats',
    },
    ['dinghy3'] = {
        ['name'] = 'Dinghy (Heist)',
        ['brand'] = 'Nagasaki',
        ['model'] = 'dinghy3',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `dinghy3`,
        ['shop'] = 'boats',
    },
    ['dinghy4'] = {
        ['name'] = 'Dinghy Yacht',
        ['brand'] = 'Nagasaki',
        ['model'] = 'dinghy4',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `dinghy4`,
        ['shop'] = 'boats',
    },
    ['suntrap'] = {
        ['name'] = 'Suntrap',
        ['brand'] = 'Shitzu',
        ['model'] = 'suntrap',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `suntrap`,
        ['shop'] = 'boats',
    },
    ['speeder'] = {
        ['name'] = 'Speeder',
        ['brand'] = 'Pegassi',
        ['model'] = 'speeder',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `speeder`,
        ['shop'] = 'boats',
    },
    ['speeder2'] = {
        ['name'] = 'Speeder Yacht',
        ['brand'] = 'Pegassi',
        ['model'] = 'speeder2',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `speeder2`,
        ['shop'] = 'boats',
    },
    ['longfin'] = {
        ['name'] = 'Longfin',
        ['brand'] = 'Shitzu',
        ['model'] = 'longfin',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `longfin`,
        ['shop'] = 'boats',
    },
    ['toro'] = {
        ['name'] = 'Toro',
        ['brand'] = 'Lampadati',
        ['model'] = 'toro',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `toro`,
        ['shop'] = 'boats',
    },
    ['toro2'] = {
        ['name'] = 'Toro Yacht',
        ['brand'] = 'Lampadati',
        ['model'] = 'toro2',
        ['price'] = 40000,
        ['category'] = 'boats',
        ['categoryLabel'] = 'Boats',
        ['hash'] = `toro2`,
        ['shop'] = 'boats',
    },
    -- helicopters
    ['buzzard2'] = {
        ['name'] = 'Buzzard',
        ['brand'] = 'Unknown',
        ['model'] = 'buzzard2',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `buzzard2`,
        ['shop'] = 'air',
    },
    ['frogger'] = {
        ['name'] = 'Frogger',
        ['brand'] = 'Unknown',
        ['model'] = 'frogger',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `frogger`,
        ['shop'] = 'air',
    },
    ['frogger2'] = {
        ['name'] = 'Frogger (Trevor Philips Enterprises)',
        ['brand'] = 'Unknown',
        ['model'] = 'frogger2',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `frogger2`,
        ['shop'] = 'air',
    },
    ['maverick'] = {
        ['name'] = 'Maverick',
        ['brand'] = 'Unknown',
        ['model'] = 'maverick',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `maverick`,
        ['shop'] = 'air',
    },
    ['swift'] = {
        ['name'] = 'Swift',
        ['brand'] = 'Buckingham',
        ['model'] = 'swift',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `swift`,
        ['shop'] = 'air',
    },
    ['swift2'] = {
        ['name'] = 'Swift Deluxe',
        ['brand'] = 'Buckingham',
        ['model'] = 'swift2',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `swift2`,
        ['shop'] = 'air',
    },
    ['seasparrow'] = {
        ['name'] = 'Sea Sparrow',
        ['brand'] = 'Unknown',
        ['model'] = 'seasparrow',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `seasparrow`,
        ['shop'] = 'air',
    },
    ['seasparrow2'] = {
        ['name'] = 'Sparrow',
        ['brand'] = 'Unknown',
        ['model'] = 'seasparrow2',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `seasparrow2`,
        ['shop'] = 'air',
    },
    ['seasparrow3'] = {
        ['name'] = 'Sparrow (Prop)',
        ['brand'] = 'Unknown',
        ['model'] = 'seasparrow3',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `seasparrow3`,
        ['shop'] = 'air',
    },
    ['supervolito'] = {
        ['name'] = 'SuperVolito',
        ['brand'] = 'Buckingham',
        ['model'] = 'supervolito',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `supervolito`,
        ['shop'] = 'air',
    },
    ['supervolito2'] = {
        ['name'] = 'SuperVolito Carbon',
        ['brand'] = 'Buckingham',
        ['model'] = 'supervolito2',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `supervolito2`,
        ['shop'] = 'air',
    },
    ['volatus'] = {
        ['name'] = 'Volatus',
        ['brand'] = 'Buckingham',
        ['model'] = 'volatus',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `volatus`,
        ['shop'] = 'air',
    },
    ['havok'] = {
        ['name'] = 'Havok',
        ['brand'] = 'Nagasaki',
        ['model'] = 'havok',
        ['price'] = 52000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `havok`,
        ['shop'] = 'air',
    },
    -- Planes
    ['duster'] = {
        ['name'] = 'Duster',
        ['brand'] = 'Unknown',
        ['model'] = 'duster',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `duster`,
        ['shop'] = 'air',
    },
    ['luxor'] = {
        ['name'] = 'Luxor',
        ['brand'] = 'Buckingham',
        ['model'] = 'luxor',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `luxor`,
        ['shop'] = 'air',
    },
    ['luxor2'] = {
        ['name'] = 'Luxor Deluxe',
        ['brand'] = 'Buckingham',
        ['model'] = 'luxor2',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `luxor2`,
        ['shop'] = 'air',
    },
    ['stunt'] = {
        ['name'] = 'Mallard',
        ['brand'] = 'Unknown',
        ['model'] = 'stunt',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `stunt`,
        ['shop'] = 'air',
    },
    ['mammatus'] = {
        ['name'] = 'Mammatus',
        ['brand'] = 'Unknown',
        ['model'] = 'mammatus',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `mammatus`,
        ['shop'] = 'air',
    },
    ['velum'] = {
        ['name'] = 'Velum',
        ['brand'] = 'Unknown',
        ['model'] = 'velum',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `velum`,
        ['shop'] = 'air',
    },
    ['velum2'] = {
        ['name'] = 'Velum 5-Seater',
        ['brand'] = 'Unknown',
        ['model'] = 'velum2',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `velum2`,
        ['shop'] = 'air',
    },
    ['shamal'] = {
        ['name'] = 'Shamal',
        ['brand'] = 'Buckingham',
        ['model'] = 'shamal',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `shamal`,
        ['shop'] = 'air',
    },
    ['vestra'] = {
        ['name'] = 'Vestra',
        ['brand'] = 'Buckingham',
        ['model'] = 'vestra',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `vestra`,
        ['shop'] = 'air',
    },
    ['dodo'] = {
        ['name'] = 'Dodo',
        ['brand'] = 'Mammoth',
        ['model'] = 'dodo',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `dodo`,
        ['shop'] = 'air',
    },
    ['howard'] = {
        ['name'] = 'Howard NX-25',
        ['brand'] = 'Buckingham',
        ['model'] = 'howard',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `howard`,
        ['shop'] = 'air',
    },
    ['alphaz1'] = {
        ['name'] = 'Alpha-Z1',
        ['brand'] = 'Buckingham',
        ['model'] = 'alphaz1',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `alphaz1`,
        ['shop'] = 'air',
    },
    ['nimbus'] = {
        ['name'] = 'Nimbus',
        ['brand'] = 'Buckingham',
        ['model'] = 'nimbus',
        ['price'] = 45000,
        ['category'] = 'planes',
        ['categoryLabel'] = 'Planes',
        ['hash'] = `nimbus`,
        ['shop'] = 'air',
    },
    ['brioso3'] = {          --DLC +set sv_enforceGameBuild 2699 (and below)
        ['name'] = 'Brioso 300 Widebody',
        ['brand'] = 'Grotti',
        ['model'] = 'brioso3',
        ['price'] = 125000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `brioso3`,
        ['shop'] = 'pdm',
    },
    ['conada'] = {
        ['name'] = 'Conada',
        ['brand'] = 'Buckingham',
        ['model'] = 'conada',
        ['price'] = 115000,
        ['category'] = 'helicopters',
        ['categoryLabel'] = 'Helicopters',
        ['hash'] = `conada`,
        ['shop'] = 'air',
    },
    ['corsita'] = {
        ['name'] = 'Corsita',
        ['brand'] = 'Lampadati',
        ['model'] = 'corsita',
        ['price'] = 90000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `corsita`,
        ['shop'] = 'luxury',
    },
    ['draugur'] = {
        ['name'] = 'Draugur',
        ['brand'] = 'Declasse',
        ['model'] = 'draugur',
        ['price'] = 99000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Off Road',
        ['hash'] = `draugur`,
        ['shop'] = 'pdm',
    },
    ['greenwood'] = {
        ['name'] = 'Greenwood',
        ['brand'] = 'Bravado',
        ['model'] = 'greenwood',
        ['price'] = 105000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `greenwood`,
        ['shop'] = 'pdm',
    },
    ['kanjosj'] = {
        ['name'] = 'Kanjo SJ',
        ['brand'] = 'Dinka',
        ['model'] = 'kanjosj',
        ['price'] = 143000,
        ['category'] = 'coupes',
        ['categoryLabel'] = 'Coupes',
        ['hash'] = `kanjosj`,
        ['shop'] = 'pdm',
    },
    ['lm87'] = {
        ['name'] = 'LM87',
        ['brand'] = 'Benefactor',
        ['model'] = 'lm87',
        ['price'] = 155000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `lm87`,
        ['shop'] = 'luxury',
    },
    ['omnisegt'] = {
        ['name'] = 'Omnis e-GT',
        ['brand'] = 'Obey',
        ['model'] = 'omnisegt',
        ['price'] = 185000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `omnisegt`,
        ['shop'] = 'luxury',
    },
    ['postlude'] = {
        ['name'] = 'Postlude',
        ['brand'] = 'Dinka',
        ['model'] = 'postlude',
        ['price'] = 90000,
        ['category'] = 'coupes',
        ['categoryLabel'] = 'Coupes',
        ['hash'] = `postlude`,
        ['shop'] = 'pdm',
    },
    ['rhinehart'] = {
        ['name'] = 'Rhinehart',
        ['brand'] = 'Übermacht',
        ['model'] = 'rhinehart ',
        ['price'] = 105000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `rhinehart`,
        ['shop'] = 'pdm',
    },
    ['ruiner4'] = {
        ['name'] = 'Ruiner ZZ-8',
        ['brand'] = 'Imponte',
        ['model'] = 'ruiner4',
        ['price'] = 85000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `ruiner4`,
        ['shop'] = 'pdm',
    },
    ['sentinel4'] = {
        ['name'] = 'Sentinel Classic Widebody',
        ['brand'] = 'Übermacht',
        ['model'] = 'sentinel4',
        ['price'] = 140000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `sentinel4`,
        ['shop'] = 'luxury',
    },
    ['sm722'] = {
        ['name'] = 'SM722',
        ['brand'] = 'Benefactor',
        ['model'] = 'sm722',
        ['price'] = 125000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `sm722`,
        ['shop'] = 'luxury',
    },
    ['tenf'] = {
        ['name'] = '10F',
        ['brand'] = 'Obey',
        ['model'] = 'tenf',
        ['price'] = 185000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `tenf`,
        ['shop'] = 'luxury',
    },
    ['tenf2'] = {
        ['name'] = '10F Widebody',
        ['brand'] = 'Obey',
        ['model'] = 'tenf2',
        ['price'] = 215000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `tenf2`,
        ['shop'] = 'luxury',
    },
    ['torero2'] = {
        ['name'] = 'Torero XO',
        ['brand'] = 'Pegassi',
        ['model'] = 'torero2',
        ['price'] = 245000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `torero2`,
        ['shop'] = 'luxury',
    },
    ['vigero2'] = {
        ['name'] = 'Vigero ZX',
        ['brand'] = 'Declasse',
        ['model'] = 'vigero2',
        ['price'] = 105000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `vigero2`,
        ['shop'] = 'pdm',
    },
    ['weevil2'] = {
        ['name'] = 'Weevil Custom',
        ['brand'] = 'BF',
        ['model'] = 'weevil2',
        ['price'] = 95000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `weevil2`,
        ['shop'] = 'pdm',
    },
    ['hauler'] = {
        ['name'] = 'Hauler',
        ['brand'] = 'Jobuilt',
        ['model'] = 'hauler',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `hauler`,
        ['shop'] = 'truck',
    },
    ['packer'] = {
        ['name'] = 'Packer',
        ['brand'] = 'MTL',
        ['model'] = 'packer',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `packer`,
        ['shop'] = 'truck',
    },
    ['stockade'] = {
        ['name'] = 'Stockade',
        ['brand'] = 'Brute',
        ['model'] = 'stockade',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `stockade`,
        ['shop'] = 'truck',
    },
    ['biff'] = {
        ['name'] = 'Biff',
        ['brand'] = 'Brute',
        ['model'] = 'biff',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `biff`,
        ['shop'] = 'truck',
    },
    ['phantom'] = {
        ['name'] = 'Phantom',
        ['brand'] = 'Jobuilt',
        ['model'] = 'phantom',
        ['price'] = 100000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `phantom`,
        ['shop'] = 'truck',
    },
    ['phantom3'] = {
        ['name'] = 'Phantom Custom',
        ['brand'] = 'Jobuilt',
        ['model'] = 'phantom3',
        ['price'] = 110000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `phantom3`,
        ['shop'] = 'truck',
    },
    ['benson'] = {
        ['name'] = 'Benson',
        ['brand'] = 'Vapid',
        ['model'] = 'benson',
        ['price'] = 55000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `benson`,
        ['shop'] = 'truck',
    },
    ['mule'] = {
        ['name'] = 'Mule',
        ['brand'] = 'Maibatsu',
        ['model'] = 'mule',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule`,
        ['shop'] = 'truck',
    },
    ['mule2'] = {
        ['name'] = 'Mule with Drop Door',
        ['brand'] = 'Maibatsu',
        ['model'] = 'mule2',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule2`,
        ['shop'] = 'truck',
    },
    ['mule3'] = {
        ['name'] = 'Mule with Swinging Doors',
        ['brand'] = 'Maibatsu',
        ['model'] = 'mule3',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule3`,
        ['shop'] = 'truck',
    },
    ['mule4'] = {
        ['name'] = 'Mule with Swinging Doors & Side Step',
        ['brand'] = 'Maibatsu',
        ['model'] = 'mule4',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule4`,
        ['shop'] = 'truck',
    },
    ['mule5'] = {
        ['name'] = 'Mule with Swinging Doors & Step Bumper',
        ['brand'] = 'Maibatsu',
        ['model'] = 'mule5',
        ['price'] = 40000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `mule5`,
        ['shop'] = 'truck',
    },
    ['pounder'] = {
        ['name'] = 'Pounder',
        ['brand'] = 'MTL',
        ['model'] = 'pounder',
        ['price'] = 55000,
        ['category'] = 'commercial',
        ["categoryLabel"] = 'Commercial',
        ['hash'] = `pounder`,
        ['shop'] = 'truck',
    },
    ['boxville'] = {
        ['name'] = 'Boxville LSDWP',
        ['brand'] = 'Brute',
        ['model'] = 'boxville',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville`,
        ['shop'] = 'truck',
    },
    ['boxville2'] = {
        ['name'] = 'Boxville Go Postal',
        ['brand'] = 'Brute',
        ['model'] = 'boxville2',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville2`,
        ['shop'] = 'truck',
    },
    ['boxville3'] = {
        ['name'] = 'Boxville Humane Labs',
        ['brand'] = 'Brute',
        ['model'] = 'boxville3',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville3`,
        ['shop'] = 'truck',
    },
    ['boxville4'] = {
        ['name'] = 'Boxville Post OP',
        ['brand'] = 'Brute',
        ['model'] = 'boxville4',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville4`,
        ['shop'] = 'truck',
    },
    ['boxville5'] = {
        ['name'] = 'Armored Boxville',
        ['brand'] = 'Brute',
        ['model'] = 'boxville5',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `boxville5`,
        ['shop'] = 'truck',
    },
    ['pony'] = {
        ['name'] = 'Pony',
        ['brand'] = 'Brute',
        ['model'] = 'pony',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `pony`,
        ['shop'] = 'truck',
    },
    ['pony2'] = {
        ['name'] = 'Pony (Smoke on the water)',
        ['brand'] = 'Brute',
        ['model'] = 'pony2',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Vans',
        ['hash'] = `pony2`,
        ['shop'] = 'truck',
    },
    ['taco'] = {
        ['name'] = 'Taco Truck',
        ['brand'] = 'Brute',
        ['model'] = 'taco',
        ['price'] = 45000,
        ['category'] = 'vans',
        ["categoryLabel"] = 'Food Truck',
        ['hash'] = `taco`,
        ['shop'] = 'truck',
    },
    ['cutter'] = {
        ['name'] = 'cutter',
        ['brand'] = 'HVY',
        ['model'] = 'cutter',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `cutter`,
        ['shop'] = 'truck',
    },
    ['handler'] = {
        ['name'] = 'Dock Handler',
        ['brand'] = 'HVY',
        ['model'] = 'handler',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `handler`,
        ['shop'] = 'truck',
    },
    ['bulldozer'] = {
        ['name'] = 'Bulldozer',
        ['brand'] = 'HVY',
        ['model'] = 'bulldozer',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `bulldozer`,
        ['shop'] = 'truck',
    },
    ['dump'] = {
        ['name'] = 'Dump Truck (Off Road)',
        ['brand'] = 'HVY',
        ['model'] = 'dump',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `dump`,
        ['shop'] = 'truck',
    },
    ['flatbed'] = {
        ['name'] = 'Flatbed Truck',
        ['brand'] = 'MTL',
        ['model'] = 'flatbed',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `flatbed`,
        ['shop'] = 'truck',
    },
    ['guardian'] = {
        ['name'] = 'Guardian',
        ['brand'] = 'Vapid',
        ['model'] = 'guardian',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `guardian`,
        ['shop'] = 'truck',
    },
    ['mixer'] = {
        ['name'] = 'Cement Mixer',
        ['brand'] = 'HVY',
        ['model'] = 'mixer',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `mixer`,
        ['shop'] = 'truck',
    },
    ['mixer2'] = {
        ['name'] = 'Cement Mixer 2',
        ['brand'] = 'HVY',
        ['model'] = 'mixer2',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `mixer2`,
        ['shop'] = 'truck',
    },
    ['rubble'] = {
        ['name'] = 'Dump Truck (Street Legal)',
        ['brand'] = 'Jobuilt',
        ['model'] = 'rubble',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `rubble`,
        ['shop'] = 'truck',
    },
    ['tiptruck'] = {
        ['name'] = 'Dump Truck (Street Legal)',
        ['brand'] = 'Brute',
        ['model'] = 'tiptruck',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `tiptruck`,
        ['shop'] = 'truck',
    },
    ['tiptruck2'] = {
        ['name'] = 'Dump Truck (Street Legal)',
        ['brand'] = 'MTL',
        ['model'] = 'tiptruck2',
        ['price'] = 30000,
        ['category'] = 'industrial',
        ["categoryLabel"] = 'Industrial',
        ['hash'] = `tiptruck2`,
        ['shop'] = 'truck',
    },
